/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { DepositableDelegateProxy } from "../DepositableDelegateProxy";

export class DepositableDelegateProxy__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DepositableDelegateProxy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DepositableDelegateProxy;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "proxyType",
    outputs: [
      {
        name: "proxyTypeId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isDepositable",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "implementation",
    outputs: [
      {
        name: "codeAddr",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    payable: true,
    stateMutability: "payable",
    type: "fallback",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        name: "value",
        type: "uint256",
      },
    ],
    name: "ProxyDeposit",
    type: "event",
  },
];
