/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFeed } from "../IFeed";

export class IFeed__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IFeed {
    return new Contract(address, _abi, signerOrProvider) as IFeed;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "base",
        type: "address",
      },
      {
        name: "quote",
        type: "address",
      },
    ],
    name: "get",
    outputs: [
      {
        name: "xrt",
        type: "uint128",
      },
      {
        name: "when",
        type: "uint64",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ratePrecision",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
];
