/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFIFSResolvingRegistrar } from "../IFIFSResolvingRegistrar";

export class IFIFSResolvingRegistrar__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFIFSResolvingRegistrar {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFIFSResolvingRegistrar;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_subnode",
        type: "bytes32",
      },
      {
        name: "_owner",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_subnode",
        type: "bytes32",
      },
      {
        name: "_owner",
        type: "address",
      },
      {
        name: "_resolver",
        type: "address",
      },
    ],
    name: "registerWithResolver",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
