/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { IKernelEvents } from "../IKernelEvents";

export class IKernelEvents__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<IKernelEvents> {
    return super.deploy(overrides || {}) as Promise<IKernelEvents>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IKernelEvents {
    return super.attach(address) as IKernelEvents;
  }
  connect(signer: Signer): IKernelEvents__factory {
    return super.connect(signer) as IKernelEvents__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKernelEvents {
    return new Contract(address, _abi, signerOrProvider) as IKernelEvents;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "namespace",
        type: "bytes32",
      },
      {
        indexed: true,
        name: "appId",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "app",
        type: "address",
      },
    ],
    name: "SetApp",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603580601d6000396000f3006080604052600080fd00a165627a7a723058205213abc0d6822be5dc75f466d8ceea9e89ce44e52fc54a5d6c08684d9fa64b2d0029";
