/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITollgate } from "../ITollgate";

export class ITollgate__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITollgate {
    return new Contract(address, _abi, signerOrProvider) as ITollgate;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "CHANGE_DESTINATION_ROLE",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_feeToken",
        type: "address",
      },
      {
        name: "_feeAmount",
        type: "uint256",
      },
      {
        name: "_feeDestination",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "CHANGE_AMOUNT_ROLE",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
