/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ArrayUtilsInterface extends ethers.utils.Interface {
  functions: {
    "UNVERIFIABLE_ADDRESS()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "UNVERIFIABLE_ADDRESS",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "UNVERIFIABLE_ADDRESS",
    data: BytesLike
  ): Result;

  events: {};
}

export class ArrayUtils extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ArrayUtilsInterface;

  functions: {
    UNVERIFIABLE_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    "UNVERIFIABLE_ADDRESS()"(overrides?: CallOverrides): Promise<[string]>;
  };

  UNVERIFIABLE_ADDRESS(overrides?: CallOverrides): Promise<string>;

  "UNVERIFIABLE_ADDRESS()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    UNVERIFIABLE_ADDRESS(overrides?: CallOverrides): Promise<string>;

    "UNVERIFIABLE_ADDRESS()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    UNVERIFIABLE_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    "UNVERIFIABLE_ADDRESS()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    UNVERIFIABLE_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "UNVERIFIABLE_ADDRESS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
