/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DAOFactoryInterface extends ethers.utils.Interface {
  functions: {
    "baseACL()": FunctionFragment;
    "newDAO(address)": FunctionFragment;
    "regFactory()": FunctionFragment;
    "baseKernel()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "baseACL", values?: undefined): string;
  encodeFunctionData(functionFragment: "newDAO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "regFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseKernel",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "baseACL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newDAO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "regFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseKernel", data: BytesLike): Result;

  events: {
    "DeployDAO(address)": EventFragment;
    "DeployEVMScriptRegistry(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeployDAO"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployEVMScriptRegistry"): EventFragment;
}

export class DAOFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DAOFactoryInterface;

  functions: {
    baseACL(overrides?: CallOverrides): Promise<[string]>;

    "baseACL()"(overrides?: CallOverrides): Promise<[string]>;

    newDAO(_root: string, overrides?: Overrides): Promise<ContractTransaction>;

    "newDAO(address)"(
      _root: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    regFactory(overrides?: CallOverrides): Promise<[string]>;

    "regFactory()"(overrides?: CallOverrides): Promise<[string]>;

    baseKernel(overrides?: CallOverrides): Promise<[string]>;

    "baseKernel()"(overrides?: CallOverrides): Promise<[string]>;
  };

  baseACL(overrides?: CallOverrides): Promise<string>;

  "baseACL()"(overrides?: CallOverrides): Promise<string>;

  newDAO(_root: string, overrides?: Overrides): Promise<ContractTransaction>;

  "newDAO(address)"(
    _root: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  regFactory(overrides?: CallOverrides): Promise<string>;

  "regFactory()"(overrides?: CallOverrides): Promise<string>;

  baseKernel(overrides?: CallOverrides): Promise<string>;

  "baseKernel()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    baseACL(overrides?: CallOverrides): Promise<string>;

    "baseACL()"(overrides?: CallOverrides): Promise<string>;

    newDAO(_root: string, overrides?: CallOverrides): Promise<string>;

    "newDAO(address)"(
      _root: string,
      overrides?: CallOverrides
    ): Promise<string>;

    regFactory(overrides?: CallOverrides): Promise<string>;

    "regFactory()"(overrides?: CallOverrides): Promise<string>;

    baseKernel(overrides?: CallOverrides): Promise<string>;

    "baseKernel()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DeployDAO(dao: null): EventFilter;

    DeployEVMScriptRegistry(reg: null): EventFilter;
  };

  estimateGas: {
    baseACL(overrides?: CallOverrides): Promise<BigNumber>;

    "baseACL()"(overrides?: CallOverrides): Promise<BigNumber>;

    newDAO(_root: string, overrides?: Overrides): Promise<BigNumber>;

    "newDAO(address)"(_root: string, overrides?: Overrides): Promise<BigNumber>;

    regFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "regFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    baseKernel(overrides?: CallOverrides): Promise<BigNumber>;

    "baseKernel()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baseACL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseACL()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newDAO(_root: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "newDAO(address)"(
      _root: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    regFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "regFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseKernel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseKernel()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
