/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DepositableStorageInterface extends ethers.utils.Interface {
  functions: {
    "isDepositable()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isDepositable",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "isDepositable",
    data: BytesLike
  ): Result;

  events: {};
}

export class DepositableStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DepositableStorageInterface;

  functions: {
    isDepositable(overrides?: CallOverrides): Promise<[boolean]>;

    "isDepositable()"(overrides?: CallOverrides): Promise<[boolean]>;
  };

  isDepositable(overrides?: CallOverrides): Promise<boolean>;

  "isDepositable()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    isDepositable(overrides?: CallOverrides): Promise<boolean>;

    "isDepositable()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isDepositable(overrides?: CallOverrides): Promise<BigNumber>;

    "isDepositable()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isDepositable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isDepositable()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
