/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ERC1271Interface extends ethers.utils.Interface {
  functions: {
    "ERC1271_INTERFACE_ID()": FunctionFragment;
    "isValidSignature(bytes32,bytes)": FunctionFragment;
    "ERC1271_RETURN_INVALID_SIGNATURE()": FunctionFragment;
    "ERC1271_RETURN_VALID_SIGNATURE()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ERC1271_INTERFACE_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1271_RETURN_INVALID_SIGNATURE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC1271_INTERFACE_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1271_RETURN_INVALID_SIGNATURE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    data: BytesLike
  ): Result;

  events: {};
}

export class ERC1271 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ERC1271Interface;

  functions: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<[string]>;

    "ERC1271_INTERFACE_ID()"(overrides?: CallOverrides): Promise<[string]>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "isValidSignature(bytes32,bytes)"(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "ERC1271_RETURN_INVALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

  "ERC1271_INTERFACE_ID()"(overrides?: CallOverrides): Promise<string>;

  isValidSignature(
    _hash: BytesLike,
    _signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "isValidSignature(bytes32,bytes)"(
    _hash: BytesLike,
    _signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  ERC1271_RETURN_INVALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

  "ERC1271_RETURN_INVALID_SIGNATURE()"(
    overrides?: CallOverrides
  ): Promise<string>;

  ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

  "ERC1271_RETURN_VALID_SIGNATURE()"(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<string>;

    "ERC1271_INTERFACE_ID()"(overrides?: CallOverrides): Promise<string>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "isValidSignature(bytes32,bytes)"(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<string>;

    "ERC1271_RETURN_INVALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<string>;

    ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ERC1271_INTERFACE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "ERC1271_INTERFACE_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isValidSignature(bytes32,bytes)"(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ERC1271_RETURN_INVALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC1271_INTERFACE_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ERC1271_INTERFACE_ID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isValidSignature(bytes32,bytes)"(
      _hash: BytesLike,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC1271_RETURN_INVALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ERC1271_RETURN_INVALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
