/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface EVMScriptRegistryFactoryInterface extends ethers.utils.Interface {
  functions: {
    "baseReg()": FunctionFragment;
    "newEVMScriptRegistry(address)": FunctionFragment;
    "baseCallScript()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "baseReg", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newEVMScriptRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "baseCallScript",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "baseReg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newEVMScriptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseCallScript",
    data: BytesLike
  ): Result;

  events: {};
}

export class EVMScriptRegistryFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: EVMScriptRegistryFactoryInterface;

  functions: {
    baseReg(overrides?: CallOverrides): Promise<[string]>;

    "baseReg()"(overrides?: CallOverrides): Promise<[string]>;

    newEVMScriptRegistry(
      _dao: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "newEVMScriptRegistry(address)"(
      _dao: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    baseCallScript(overrides?: CallOverrides): Promise<[string]>;

    "baseCallScript()"(overrides?: CallOverrides): Promise<[string]>;
  };

  baseReg(overrides?: CallOverrides): Promise<string>;

  "baseReg()"(overrides?: CallOverrides): Promise<string>;

  newEVMScriptRegistry(
    _dao: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "newEVMScriptRegistry(address)"(
    _dao: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  baseCallScript(overrides?: CallOverrides): Promise<string>;

  "baseCallScript()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    baseReg(overrides?: CallOverrides): Promise<string>;

    "baseReg()"(overrides?: CallOverrides): Promise<string>;

    newEVMScriptRegistry(
      _dao: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "newEVMScriptRegistry(address)"(
      _dao: string,
      overrides?: CallOverrides
    ): Promise<string>;

    baseCallScript(overrides?: CallOverrides): Promise<string>;

    "baseCallScript()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    baseReg(overrides?: CallOverrides): Promise<BigNumber>;

    "baseReg()"(overrides?: CallOverrides): Promise<BigNumber>;

    newEVMScriptRegistry(
      _dao: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "newEVMScriptRegistry(address)"(
      _dao: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    baseCallScript(overrides?: CallOverrides): Promise<BigNumber>;

    "baseCallScript()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baseReg(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseReg()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newEVMScriptRegistry(
      _dao: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "newEVMScriptRegistry(address)"(
      _dao: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    baseCallScript(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseCallScript()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
