/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEVMScriptExecutorInterface extends ethers.utils.Interface {
  functions: {
    "execScript(bytes,bytes,address[])": FunctionFragment;
    "executorType()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "execScript",
    values: [BytesLike, BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executorType",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "execScript", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executorType",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEVMScriptExecutor extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEVMScriptExecutorInterface;

  functions: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "execScript(bytes,bytes,address[])"(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executorType(overrides?: CallOverrides): Promise<[string]>;

    "executorType()"(overrides?: CallOverrides): Promise<[string]>;
  };

  execScript(
    script: BytesLike,
    input: BytesLike,
    blacklist: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "execScript(bytes,bytes,address[])"(
    script: BytesLike,
    input: BytesLike,
    blacklist: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executorType(overrides?: CallOverrides): Promise<string>;

  "executorType()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    "execScript(bytes,bytes,address[])"(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    executorType(overrides?: CallOverrides): Promise<string>;

    "executorType()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "execScript(bytes,bytes,address[])"(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    executorType(overrides?: CallOverrides): Promise<BigNumber>;

    "executorType()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execScript(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "execScript(bytes,bytes,address[])"(
      script: BytesLike,
      input: BytesLike,
      blacklist: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executorType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "executorType()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
