/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IForwarderInterface extends ethers.utils.Interface {
  functions: {
    "canForward(address,bytes)": FunctionFragment;
    "forward(bytes)": FunctionFragment;
    "isForwarder()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canForward",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "forward", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isForwarder",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "canForward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "forward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isForwarder",
    data: BytesLike
  ): Result;

  events: {};
}

export class IForwarder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IForwarderInterface;

  functions: {
    canForward(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "canForward(address,bytes)"(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    forward(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "forward(bytes)"(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isForwarder(overrides?: CallOverrides): Promise<[boolean]>;

    "isForwarder()"(overrides?: CallOverrides): Promise<[boolean]>;
  };

  canForward(
    sender: string,
    evmCallScript: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "canForward(address,bytes)"(
    sender: string,
    evmCallScript: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  forward(
    evmCallScript: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "forward(bytes)"(
    evmCallScript: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isForwarder(overrides?: CallOverrides): Promise<boolean>;

  "isForwarder()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    canForward(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canForward(address,bytes)"(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    forward(evmCallScript: BytesLike, overrides?: CallOverrides): Promise<void>;

    "forward(bytes)"(
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    isForwarder(overrides?: CallOverrides): Promise<boolean>;

    "isForwarder()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    canForward(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canForward(address,bytes)"(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    forward(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "forward(bytes)"(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    "isForwarder()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    canForward(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canForward(address,bytes)"(
      sender: string,
      evmCallScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    forward(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "forward(bytes)"(
      evmCallScript: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isForwarder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isForwarder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
