/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IIssuanceInterface extends ethers.utils.Interface {
  functions: {
    "UPDATE_SETTINGS_ROLE()": FunctionFragment;
    "initialize(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "UPDATE_SETTINGS_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPDATE_SETTINGS_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class IIssuance extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IIssuanceInterface;

  functions: {
    UPDATE_SETTINGS_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "UPDATE_SETTINGS_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,uint256,uint256)"(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  UPDATE_SETTINGS_ROLE(overrides?: CallOverrides): Promise<string>;

  "UPDATE_SETTINGS_ROLE()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    _commonPoolTokenManager: string,
    _commonPoolVault: string,
    _targetRatio: BigNumberish,
    _maxAdjustmentRatioPerSecond: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,uint256,uint256)"(
    _commonPoolTokenManager: string,
    _commonPoolVault: string,
    _targetRatio: BigNumberish,
    _maxAdjustmentRatioPerSecond: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    UPDATE_SETTINGS_ROLE(overrides?: CallOverrides): Promise<string>;

    "UPDATE_SETTINGS_ROLE()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,uint256,uint256)"(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    UPDATE_SETTINGS_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "UPDATE_SETTINGS_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,uint256,uint256)"(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    UPDATE_SETTINGS_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "UPDATE_SETTINGS_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,uint256,uint256)"(
      _commonPoolTokenManager: string,
      _commonPoolVault: string,
      _targetRatio: BigNumberish,
      _maxAdjustmentRatioPerSecond: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
