/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MiniMeTokenFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createCloneToken(address,uint256,string,uint8,string,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createCloneToken",
    values: [string, BigNumberish, string, BigNumberish, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCloneToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class MiniMeTokenFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MiniMeTokenFactoryInterface;

  functions: {
    createCloneToken(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createCloneToken(address,uint256,string,uint8,string,bool)"(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  createCloneToken(
    _parentToken: string,
    _snapshotBlock: BigNumberish,
    _tokenName: string,
    _decimalUnits: BigNumberish,
    _tokenSymbol: string,
    _transfersEnabled: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createCloneToken(address,uint256,string,uint8,string,bool)"(
    _parentToken: string,
    _snapshotBlock: BigNumberish,
    _tokenName: string,
    _decimalUnits: BigNumberish,
    _tokenSymbol: string,
    _transfersEnabled: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    createCloneToken(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    "createCloneToken(address,uint256,string,uint8,string,bool)"(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createCloneToken(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createCloneToken(address,uint256,string,uint8,string,bool)"(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createCloneToken(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createCloneToken(address,uint256,string,uint8,string,bool)"(
      _parentToken: string,
      _snapshotBlock: BigNumberish,
      _tokenName: string,
      _decimalUnits: BigNumberish,
      _tokenSymbol: string,
      _transfersEnabled: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
