/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SignatureValidatorInterface extends ethers.utils.Interface {
  functions: {
    "ERC1271_RETURN_VALID_SIGNATURE()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC1271_RETURN_VALID_SIGNATURE",
    data: BytesLike
  ): Result;

  events: {};
}

export class SignatureValidator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SignatureValidatorInterface;

  functions: {
    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

  "ERC1271_RETURN_VALID_SIGNATURE()"(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    ERC1271_RETURN_VALID_SIGNATURE(overrides?: CallOverrides): Promise<string>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC1271_RETURN_VALID_SIGNATURE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ERC1271_RETURN_VALID_SIGNATURE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
