/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenManagerInterface extends ethers.utils.Interface {
  functions: {
    "hasInitialized()": FunctionFragment;
    "MAX_VESTINGS_PER_ADDRESS()": FunctionFragment;
    "spendableBalanceOf(address)": FunctionFragment;
    "assignVested(address,uint256,uint64,uint64,uint64,bool)": FunctionFragment;
    "getEVMScriptExecutor(bytes)": FunctionFragment;
    "getRecoveryVault()": FunctionFragment;
    "getVesting(address,uint256)": FunctionFragment;
    "mint(address,uint256)": FunctionFragment;
    "onTransfer(address,address,uint256)": FunctionFragment;
    "transferableBalance(address,uint256)": FunctionFragment;
    "allowRecoverability(address)": FunctionFragment;
    "appId()": FunctionFragment;
    "ISSUE_ROLE()": FunctionFragment;
    "getInitializationBlock()": FunctionFragment;
    "vestingsLengths(address)": FunctionFragment;
    "transferToVault(address)": FunctionFragment;
    "burn(address,uint256)": FunctionFragment;
    "canPerform(address,bytes32,uint256[])": FunctionFragment;
    "getEVMScriptRegistry()": FunctionFragment;
    "ASSIGN_ROLE()": FunctionFragment;
    "BURN_ROLE()": FunctionFragment;
    "assign(address,uint256)": FunctionFragment;
    "canForward(address,bytes)": FunctionFragment;
    "issue(uint256)": FunctionFragment;
    "kernel()": FunctionFragment;
    "forward(bytes)": FunctionFragment;
    "onApprove(address,address,uint256)": FunctionFragment;
    "isPetrified()": FunctionFragment;
    "initialize(address,bool,uint256)": FunctionFragment;
    "MINT_ROLE()": FunctionFragment;
    "maxAccountTokens()": FunctionFragment;
    "REVOKE_VESTINGS_ROLE()": FunctionFragment;
    "proxyPayment(address)": FunctionFragment;
    "revokeVesting(address,uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "isForwarder()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "hasInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VESTINGS_PER_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "spendableBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assignVested",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEVMScriptExecutor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVesting",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onTransfer",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferableBalance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowRecoverability",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "appId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ISSUE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInitializationBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestingsLengths",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canPerform",
    values: [string, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEVMScriptRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSIGN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BURN_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assign",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canForward",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "issue", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "kernel", values?: undefined): string;
  encodeFunctionData(functionFragment: "forward", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "onApprove",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPetrified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "MINT_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxAccountTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVOKE_VESTINGS_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxyPayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVesting",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isForwarder",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "hasInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VESTINGS_PER_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendableBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignVested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEVMScriptExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVesting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onTransfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowRecoverability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ISSUE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInitializationBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingsLengths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canPerform", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEVMScriptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSIGN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BURN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assign", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canForward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kernel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "forward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onApprove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPetrified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MINT_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxAccountTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVOKE_VESTINGS_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxyPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isForwarder",
    data: BytesLike
  ): Result;

  events: {
    "NewVesting(address,uint256,uint256)": EventFragment;
    "RevokeVesting(address,uint256,uint256)": EventFragment;
    "ScriptResult(address,bytes,bytes,bytes)": EventFragment;
    "RecoverToVault(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewVesting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeVesting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScriptResult"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RecoverToVault"): EventFragment;
}

export class TokenManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenManagerInterface;

  functions: {
    hasInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    "hasInitialized()"(overrides?: CallOverrides): Promise<[boolean]>;

    MAX_VESTINGS_PER_ADDRESS(overrides?: CallOverrides): Promise<[BigNumber]>;

    "MAX_VESTINGS_PER_ADDRESS()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    spendableBalanceOf(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "spendableBalanceOf(address)"(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    assignVested(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assignVested(address,uint256,uint64,uint64,uint64,bool)"(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getEVMScriptExecutor(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getEVMScriptExecutor(bytes)"(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRecoveryVault(overrides?: CallOverrides): Promise<[string]>;

    "getRecoveryVault()"(overrides?: CallOverrides): Promise<[string]>;

    getVesting(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        start: BigNumber;
        cliff: BigNumber;
        vesting: BigNumber;
        revokable: boolean;
      }
    >;

    "getVesting(address,uint256)"(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        start: BigNumber;
        cliff: BigNumber;
        vesting: BigNumber;
        revokable: boolean;
      }
    >;

    mint(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mint(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onTransfer(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onTransfer(address,address,uint256)"(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferableBalance(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "transferableBalance(address,uint256)"(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    allowRecoverability(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "allowRecoverability(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    appId(overrides?: CallOverrides): Promise<[string]>;

    "appId()"(overrides?: CallOverrides): Promise<[string]>;

    ISSUE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "ISSUE_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    getInitializationBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getInitializationBlock()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    vestingsLengths(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "vestingsLengths(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferToVault(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferToVault(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    burn(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burn(address,uint256)"(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    canPerform(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "canPerform(address,bytes32,uint256[])"(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getEVMScriptRegistry(overrides?: CallOverrides): Promise<[string]>;

    "getEVMScriptRegistry()"(overrides?: CallOverrides): Promise<[string]>;

    ASSIGN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "ASSIGN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    BURN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "BURN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    assign(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assign(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    canForward(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "canForward(address,bytes)"(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    issue(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "issue(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    kernel(overrides?: CallOverrides): Promise<[string]>;

    "kernel()"(overrides?: CallOverrides): Promise<[string]>;

    forward(
      _evmScript: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "forward(bytes)"(
      _evmScript: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onApprove(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onApprove(address,address,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isPetrified(overrides?: CallOverrides): Promise<[boolean]>;

    "isPetrified()"(overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,bool,uint256)"(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    MINT_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "MINT_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    maxAccountTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxAccountTokens()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    REVOKE_VESTINGS_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "REVOKE_VESTINGS_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    proxyPayment(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "proxyPayment(address)"(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    revokeVesting(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeVesting(address,uint256)"(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    "token()"(overrides?: CallOverrides): Promise<[string]>;

    isForwarder(overrides?: CallOverrides): Promise<[boolean]>;

    "isForwarder()"(overrides?: CallOverrides): Promise<[boolean]>;
  };

  hasInitialized(overrides?: CallOverrides): Promise<boolean>;

  "hasInitialized()"(overrides?: CallOverrides): Promise<boolean>;

  MAX_VESTINGS_PER_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_VESTINGS_PER_ADDRESS()"(overrides?: CallOverrides): Promise<BigNumber>;

  spendableBalanceOf(
    _holder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "spendableBalanceOf(address)"(
    _holder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  assignVested(
    _receiver: string,
    _amount: BigNumberish,
    _start: BigNumberish,
    _cliff: BigNumberish,
    _vested: BigNumberish,
    _revokable: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assignVested(address,uint256,uint64,uint64,uint64,bool)"(
    _receiver: string,
    _amount: BigNumberish,
    _start: BigNumberish,
    _cliff: BigNumberish,
    _vested: BigNumberish,
    _revokable: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getEVMScriptExecutor(
    _script: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getEVMScriptExecutor(bytes)"(
    _script: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getRecoveryVault(overrides?: CallOverrides): Promise<string>;

  "getRecoveryVault()"(overrides?: CallOverrides): Promise<string>;

  getVesting(
    _recipient: string,
    _vestingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      start: BigNumber;
      cliff: BigNumber;
      vesting: BigNumber;
      revokable: boolean;
    }
  >;

  "getVesting(address,uint256)"(
    _recipient: string,
    _vestingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      start: BigNumber;
      cliff: BigNumber;
      vesting: BigNumber;
      revokable: boolean;
    }
  >;

  mint(
    _receiver: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mint(address,uint256)"(
    _receiver: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onTransfer(
    _from: string,
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onTransfer(address,address,uint256)"(
    _from: string,
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferableBalance(
    _holder: string,
    _time: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "transferableBalance(address,uint256)"(
    _holder: string,
    _time: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  allowRecoverability(
    _token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "allowRecoverability(address)"(
    _token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  appId(overrides?: CallOverrides): Promise<string>;

  "appId()"(overrides?: CallOverrides): Promise<string>;

  ISSUE_ROLE(overrides?: CallOverrides): Promise<string>;

  "ISSUE_ROLE()"(overrides?: CallOverrides): Promise<string>;

  getInitializationBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "getInitializationBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  vestingsLengths(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "vestingsLengths(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferToVault(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferToVault(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  burn(
    _holder: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burn(address,uint256)"(
    _holder: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  canPerform(
    _sender: string,
    _role: BytesLike,
    _params: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "canPerform(address,bytes32,uint256[])"(
    _sender: string,
    _role: BytesLike,
    _params: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  getEVMScriptRegistry(overrides?: CallOverrides): Promise<string>;

  "getEVMScriptRegistry()"(overrides?: CallOverrides): Promise<string>;

  ASSIGN_ROLE(overrides?: CallOverrides): Promise<string>;

  "ASSIGN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  BURN_ROLE(overrides?: CallOverrides): Promise<string>;

  "BURN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  assign(
    _receiver: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assign(address,uint256)"(
    _receiver: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  canForward(
    _sender: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "canForward(address,bytes)"(
    _sender: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  issue(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "issue(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  kernel(overrides?: CallOverrides): Promise<string>;

  "kernel()"(overrides?: CallOverrides): Promise<string>;

  forward(
    _evmScript: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "forward(bytes)"(
    _evmScript: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onApprove(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onApprove(address,address,uint256)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isPetrified(overrides?: CallOverrides): Promise<boolean>;

  "isPetrified()"(overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _token: string,
    _transferable: boolean,
    _maxAccountTokens: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,bool,uint256)"(
    _token: string,
    _transferable: boolean,
    _maxAccountTokens: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  MINT_ROLE(overrides?: CallOverrides): Promise<string>;

  "MINT_ROLE()"(overrides?: CallOverrides): Promise<string>;

  maxAccountTokens(overrides?: CallOverrides): Promise<BigNumber>;

  "maxAccountTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

  REVOKE_VESTINGS_ROLE(overrides?: CallOverrides): Promise<string>;

  "REVOKE_VESTINGS_ROLE()"(overrides?: CallOverrides): Promise<string>;

  proxyPayment(
    arg0: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "proxyPayment(address)"(
    arg0: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  revokeVesting(
    _holder: string,
    _vestingId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeVesting(address,uint256)"(
    _holder: string,
    _vestingId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  "token()"(overrides?: CallOverrides): Promise<string>;

  isForwarder(overrides?: CallOverrides): Promise<boolean>;

  "isForwarder()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    hasInitialized(overrides?: CallOverrides): Promise<boolean>;

    "hasInitialized()"(overrides?: CallOverrides): Promise<boolean>;

    MAX_VESTINGS_PER_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_VESTINGS_PER_ADDRESS()"(overrides?: CallOverrides): Promise<BigNumber>;

    spendableBalanceOf(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "spendableBalanceOf(address)"(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assignVested(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assignVested(address,uint256,uint64,uint64,uint64,bool)"(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEVMScriptExecutor(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getEVMScriptExecutor(bytes)"(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getRecoveryVault(overrides?: CallOverrides): Promise<string>;

    "getRecoveryVault()"(overrides?: CallOverrides): Promise<string>;

    getVesting(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        start: BigNumber;
        cliff: BigNumber;
        vesting: BigNumber;
        revokable: boolean;
      }
    >;

    "getVesting(address,uint256)"(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        start: BigNumber;
        cliff: BigNumber;
        vesting: BigNumber;
        revokable: boolean;
      }
    >;

    mint(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "mint(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    onTransfer(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "onTransfer(address,address,uint256)"(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferableBalance(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transferableBalance(address,uint256)"(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allowRecoverability(
      _token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "allowRecoverability(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    appId(overrides?: CallOverrides): Promise<string>;

    "appId()"(overrides?: CallOverrides): Promise<string>;

    ISSUE_ROLE(overrides?: CallOverrides): Promise<string>;

    "ISSUE_ROLE()"(overrides?: CallOverrides): Promise<string>;

    getInitializationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitializationBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    vestingsLengths(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "vestingsLengths(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferToVault(_token: string, overrides?: CallOverrides): Promise<void>;

    "transferToVault(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    burn(
      _holder: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "burn(address,uint256)"(
      _holder: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    canPerform(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canPerform(address,bytes32,uint256[])"(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    getEVMScriptRegistry(overrides?: CallOverrides): Promise<string>;

    "getEVMScriptRegistry()"(overrides?: CallOverrides): Promise<string>;

    ASSIGN_ROLE(overrides?: CallOverrides): Promise<string>;

    "ASSIGN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    BURN_ROLE(overrides?: CallOverrides): Promise<string>;

    "BURN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    assign(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "assign(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    canForward(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canForward(address,bytes)"(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    issue(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "issue(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    kernel(overrides?: CallOverrides): Promise<string>;

    "kernel()"(overrides?: CallOverrides): Promise<string>;

    forward(_evmScript: BytesLike, overrides?: CallOverrides): Promise<void>;

    "forward(bytes)"(
      _evmScript: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    onApprove(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "onApprove(address,address,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPetrified(overrides?: CallOverrides): Promise<boolean>;

    "isPetrified()"(overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,bool,uint256)"(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    MINT_ROLE(overrides?: CallOverrides): Promise<string>;

    "MINT_ROLE()"(overrides?: CallOverrides): Promise<string>;

    maxAccountTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "maxAccountTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    REVOKE_VESTINGS_ROLE(overrides?: CallOverrides): Promise<string>;

    "REVOKE_VESTINGS_ROLE()"(overrides?: CallOverrides): Promise<string>;

    proxyPayment(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "proxyPayment(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    revokeVesting(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeVesting(address,uint256)"(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;

    isForwarder(overrides?: CallOverrides): Promise<boolean>;

    "isForwarder()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    NewVesting(
      receiver: string | null,
      vestingId: null,
      amount: null
    ): EventFilter;

    RevokeVesting(
      receiver: string | null,
      vestingId: null,
      nonVestedAmount: null
    ): EventFilter;

    ScriptResult(
      executor: string | null,
      script: null,
      input: null,
      returnData: null
    ): EventFilter;

    RecoverToVault(
      vault: string | null,
      token: string | null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {
    hasInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    "hasInitialized()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_VESTINGS_PER_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_VESTINGS_PER_ADDRESS()"(overrides?: CallOverrides): Promise<BigNumber>;

    spendableBalanceOf(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "spendableBalanceOf(address)"(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assignVested(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assignVested(address,uint256,uint64,uint64,uint64,bool)"(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getEVMScriptExecutor(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEVMScriptExecutor(bytes)"(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecoveryVault(overrides?: CallOverrides): Promise<BigNumber>;

    "getRecoveryVault()"(overrides?: CallOverrides): Promise<BigNumber>;

    getVesting(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getVesting(address,uint256)"(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mint(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onTransfer(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onTransfer(address,address,uint256)"(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferableBalance(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transferableBalance(address,uint256)"(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allowRecoverability(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowRecoverability(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    appId(overrides?: CallOverrides): Promise<BigNumber>;

    "appId()"(overrides?: CallOverrides): Promise<BigNumber>;

    ISSUE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "ISSUE_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    getInitializationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitializationBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    vestingsLengths(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "vestingsLengths(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferToVault(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "transferToVault(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    burn(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burn(address,uint256)"(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    canPerform(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canPerform(address,bytes32,uint256[])"(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEVMScriptRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    "getEVMScriptRegistry()"(overrides?: CallOverrides): Promise<BigNumber>;

    ASSIGN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "ASSIGN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    BURN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "BURN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    assign(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assign(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    canForward(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canForward(address,bytes)"(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issue(_amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "issue(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    kernel(overrides?: CallOverrides): Promise<BigNumber>;

    "kernel()"(overrides?: CallOverrides): Promise<BigNumber>;

    forward(_evmScript: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "forward(bytes)"(
      _evmScript: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onApprove(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onApprove(address,address,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isPetrified(overrides?: CallOverrides): Promise<BigNumber>;

    "isPetrified()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,bool,uint256)"(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    MINT_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "MINT_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxAccountTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "maxAccountTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    REVOKE_VESTINGS_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "REVOKE_VESTINGS_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    proxyPayment(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "proxyPayment(address)"(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    revokeVesting(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeVesting(address,uint256)"(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    "token()"(overrides?: CallOverrides): Promise<BigNumber>;

    isForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    "isForwarder()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hasInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "hasInitialized()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_VESTINGS_PER_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MAX_VESTINGS_PER_ADDRESS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    spendableBalanceOf(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "spendableBalanceOf(address)"(
      _holder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assignVested(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assignVested(address,uint256,uint64,uint64,uint64,bool)"(
      _receiver: string,
      _amount: BigNumberish,
      _start: BigNumberish,
      _cliff: BigNumberish,
      _vested: BigNumberish,
      _revokable: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getEVMScriptExecutor(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEVMScriptExecutor(bytes)"(
      _script: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecoveryVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getRecoveryVault()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVesting(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVesting(address,uint256)"(
      _recipient: string,
      _vestingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mint(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onTransfer(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onTransfer(address,address,uint256)"(
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferableBalance(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "transferableBalance(address,uint256)"(
      _holder: string,
      _time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allowRecoverability(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowRecoverability(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    appId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "appId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ISSUE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ISSUE_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInitializationBlock(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getInitializationBlock()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vestingsLengths(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "vestingsLengths(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferToVault(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferToVault(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    burn(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burn(address,uint256)"(
      _holder: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    canPerform(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canPerform(address,bytes32,uint256[])"(
      _sender: string,
      _role: BytesLike,
      _params: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEVMScriptRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEVMScriptRegistry()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ASSIGN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ASSIGN_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BURN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "BURN_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assign(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assign(address,uint256)"(
      _receiver: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    canForward(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canForward(address,bytes)"(
      _sender: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issue(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "issue(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    kernel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "kernel()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    forward(
      _evmScript: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "forward(bytes)"(
      _evmScript: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onApprove(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onApprove(address,address,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isPetrified(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isPetrified()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,bool,uint256)"(
      _token: string,
      _transferable: boolean,
      _maxAccountTokens: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    MINT_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MINT_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxAccountTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxAccountTokens()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REVOKE_VESTINGS_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "REVOKE_VESTINGS_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxyPayment(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "proxyPayment(address)"(
      arg0: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    revokeVesting(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeVesting(address,uint256)"(
      _holder: string,
      _vestingId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isForwarder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isForwarder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
